### ISSUE TITLE
[Brush-up] variable indentation settings for custom rule of `indent-in-infix-expression`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-plugin-openreachtech#48]
## Overview

* Change the indentation setting in custom rule of `indent-in-infix-expression`, which is fixed at 2, to variable.
  > `indent-in-infix-expression` で、2に固定されているインデントの設定を可変に変更する。
  
* How to implement options:
[ESLintのルールを自作しよう！](https://techblog.yahoo.co.jp/javascript/how-to-create-eslint-rules/)
  
## Spec

* Uses `context.options.indent`.
```
rules:
  openreachtech/indent-in-infix-expression:
    - errorr
    - indnet: 2 # 2/4/8
```

* Think about `tab`.
